config/routes.rb
Wilr::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :blogs

   root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :bimg1, :bimg2, :bimg3, :content
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :blog_id, :highlighted_code, :language, :name, :plain_code

  def highlight
  CodeRay.scan(self.language, self.language).html.div
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.json
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(params[:snippet])

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render json: @snippet, status: :created, location: @snippet }
      else
        format.html { render action: "new" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.json
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def coderay(text) 
    text.gsub!(/\<code(?: lang="(.+?)")?\>(.+?)\<\/code\>/m) do 
      code = CodeRay.scan($2, $1).div(:css => :class) 
      "<notextile>#{code}</notextile>" 
    end 
    return text.html_safe 
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :bimg1 %><br />
    <%= f.text_field :bimg1 %>
  </div>
  <div class="field">
    <%= f.label :bimg2 %><br />
    <%= f.text_field :bimg2 %>
  </div>
  <div class="field">
    <%= f.label :bimg3 %><br />
    <%= f.text_field :bimg3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% @blogs.each do |blog| %>
<%=blog.title%>
<%= coderay(blog.content)%>
<%end%>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= coderay(@blog.content) %>
</p>

<p>
  <b>Bimg1:</b>
  <%= @blog.bimg1 %>
</p>

<p>
  <b>Bimg2:</b>
  <%= @blog.bimg2 %>
</p>

<p>
  <b>Bimg3:</b>
  <%= @blog.bimg3 %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/home/index.html.erb
		<div class="container">
			<div class="top-pic-body">
				<div class="top-pic animated flipInY"><a href="#">
					<%=image_tag 'leo.jpg'%>
				</a></div>
				<div class="social-icon social-icon3 animated flipInY tada"><a href="#">
					<%=image_tag 'facebook.png' %>
				</a></div>
				<div class="social-icon social-icon4 animated flipInY tada"><a href="#">
					<%=image_tag "gplus_variation2.png" %>
				</a></div>
				<div class="social-icon social-icon5 animated flipInY tada"><a href="#">
					<%=image_tag 'linkedin.png'%>
				</a></div>
				<div class="social-icon social-icon6 animated flipInY tada"><a href="#">
					<%=image_tag "pinterest.png" %>
				</a></div>
				<div class="line"></div>
				<div class="line"></div>
			</div>
			<div class="title-name">LEO ROYZENGURT</div>
			<div class="title-description">Web Developer</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WHO IS LEO ROYZENGURT</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Title</a>
    <ul class="nav">
      <li class="active"><%=link_to 'Home' , "/"%> </li>
      <li><%=link_to 'Blogs', blogs_path%></li>
      <li><a href="#">Link</a></li>
    </ul>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :language %><br />
    <%= f.select :language, options_for_select([["Ruby", "ruby"], ["Python", "python"], ["JavaScript", "javascript"], ["CSS", "css"]]) %>
  </p>
  <p>
    <%= f.label :plain_code, "Source Code" %><br />
    <%= f.text_area :plain_code %>
  </p>
  <p><%= f.submit "Post Snippet" %></p>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<h1>Listing snippets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Language</th>
    <th>Plain code</th>
    <th>Highlighted code</th>
    <th>Blog</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snippets.each do |snippet| %>
  <tr>
    <td><%= snippet.name %></td>
    <td><%= snippet.language %></td>
    <td><%= snippet.plain_code %></td>
    <td><%= snippet.highlighted_code %></td>
    <td><%= snippet.blog_id %></td>
    <td><%= link_to 'Show', snippet %></td>
    <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
    <td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @snippet.name %>
</p>

<p>
  <b>Language:</b>
  <%= @snippet.language %>
</p>

<p>
  <b>Plain code:</b>
  <%= @snippet.plain_code %>
</p>

<p>
  <b>Highlighted code:</b>
  <%= @snippet.highlighted_code %>
</p>

<p>
  <b>Blog:</b>
  <%= @snippet.blog_id %>
</p>



<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>